### ISSUE TITLE
KeyError: '119114'

### ISSUE THREAD

**Issue by ljudva** [Symas/LogAnalyzer#10]
Hi guys, 

just out of courtesy, do you guys check the  for this in the log file:

Mar 15 13:26:21 is-nix-434 slapd[1331]: warning: cannot open /etc/hosts.allow: Too many open files

or the below error is something else:
.
.
('Processed:', 23, '%')
('Processed:', 24, '%')
('Processed:', 25, '%')
Traceback (most recent call last):
  File "./symasLog.py", line 1113, in <module>
    processLog( openLdapLogs, args, counters, True )
  File "./symasLog.py", line 983, in processLog
    processLine( counters, line, pos, counters.nbProcessedLines, connectionId, reqDate, args.traceMode )
  File "./symasLog.py", line 388, in processLine
    del counters.zombieSessions[sessionId] 
KeyError: '119114'

I can post the log file.

Cheer

**Comment by elecharny** [comment]
Hi,

you should check the _ulimit_ setting on your computer. It's likely to be too low.

For instance, check [that](https://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux)

**Comment by ljudva** [comment]
Hi, 

it's unlimited. Linux Mint 18..

Ideas?

**Comment by elecharny** [comment]
Le 16/03/2018 à 02:20, ljudva a écrit :
> Hi, 
> 
> it's unlimited. Linux Mint 18..


cat /proc/sys/fs/file-max ?

**Comment by ljudva** [comment]
You're early (I'm +8GMT:)

cat /proc/sys/fs/file-max 
6815744

**Comment by elecharny** [comment]
Le 16/03/2018 à 02:50, ljudva a écrit :
> You're early (I'm +8GMT:)

My daughter just vomit, it woke me up :/

> 
> cat /proc/sys/fs/file-max 
> 6815744


Hmmm... What size is your log file ?

**Comment by ljudva** [comment]
:)
Sent it yesterday to your email I've sent before...Not big, 55M...

**Comment by ljudva** [comment]
Any news guys?

so the log is about 145megs, if I split the log to about 10 megs each, oddly, not every one can be processed and they will fail with:

  File "./symasLog.py", line 388, in processLine
    del counters.zombieSessions[sessionId] 

Thoughts?

**Comment by elecharny** [comment]
I haven't got your 55Mb file.

**Comment by ljudva** [comment]
Replied now to elecharny@syma.....

**Comment by ljudva** [comment]
And sent a full log now. So, we did have an issue with a memory when we put it on the load, plus Too many open files issue form above log. The new log should not report this issues.

**Comment by elecharny** [comment]
I found a bug : zombie session get closed twice, and teh second time it does not end well. I just pushed a fix for that. The 155Mb file passes fine now.

**Comment by ljudva** [comment]
Cool, it does work indeed! 
Thank you for your time for this.
Regards
