### ISSUE TITLE
session IP not true value

### ISSUE THREAD

**Issue by platipusica** [Symas/LogAnalyzer#9]
Hi guys, 

running as:
python symasLog.py xbe --longestSearches
('Processing file : ', 'xbe')
('Processed :', 1, '%')
.
.
        -Search-----------------------------------------------
        sessionId  : 79453
        session IP : 23.123.123.123
        opId       : 2
        result     : NO_SUCH_OBJECT
        cause      : 
        duration   : 0.0ms

as seen the IP is 23.123.123.123 and should be 123.123.123.123.

python --version
Python 2.7.12

Can provide log to email. 

Please advice

Thx

**Comment by elecharny** [comment]
Yes, I'd like to have a look at the log.

**Comment by elecharny** [comment]
Fixed. We were moving forward one character too much.
